excel:
  file: cases.xlsx

logger:
  name: "python29"
  file: "python29log.txt"
  logger_level: "DEBUG"
  stream_level: "DEBUG"
  file_level: "INFO"

db:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "li19871230"
  charset: 'utf8'

user:
  mobile_phone: "15512345678"
  pwd: "12345678"

host: http://api.lemonban.com/futureloan